### PR TITLE
Update Token Url

### PR DESCRIPTION
**Pull request by lucemans**

### CODE REVIEW

**Review by gskril — APPROVED** [review]
should probably also update the title and emoji of the /dao/token page as well, but otherwise lgtm

**Comment by Jeremiegmoore** [comment]
> _ No description provided. _

**Comment by Jeremiegmoore** [comment]
Duplicate of #

**Comment by Jeremiegmoore** [comment]
<details><summary>Details</summary>
<p>



</p>
</details>

**Pull request merged**
