### PR TITLE
Created Subgraph Docs 

### PR DESCRIPTION
**Pull request by PaulieB14**
Added general information and links, entities, and query examples.

### CODE REVIEW

**Review by Arachnid — COMMENTED** [review]
Thanks for your contribution! Was this automatically generated? If so, is there a way to keep it in sync with the docs embedded in the schema?

**Comment by PaulieB14** [comment]
@Arachnid This was not auto generated.  Manual.  I think someone is working on an auto generated using Python code [GitHub - alex-pakalniskis/SubgraphSchemaEntitiesDocGenerator](https://github.com/alex-pakalniskis/SubgraphSchemaEntitiesDocGenerator). Let me know if this helps, but it only seems to organize the entities but may need more formatting.

**Comment by Arachnid** [comment]
Righto! Are you able to add the pages to SUMMARY.md so they will show up on the site?

**Comment by PaulieB14** [comment]
@arachnid. Thanks for feedback. I added to Summary.md file for you.  Let me know if you need anything else.

**Review by Arachnid — APPROVED** [review]

**Comment by PaulieB14** [comment]
@Arachnid - I changed capitalization of entities but did not do the same on the summary.md file. Should I revert your commit in order to do the changes so the website works?

**Comment by Arachnid** [comment]
Can you create a new PR?

**Comment by PaulieB14** [comment]
Sure.  I can do that right now.

**Pull request merged**
